apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sync
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: git-sync-cronjob
            image: ubuntu:24.10
            args:
            - cp /scripts/exec-cronjob.sh /opt/exec-cronjob.sh 
            - chmod +x /opt/exec-cronjob.sh 
            - ./opt/exec-cronjob.sh
            volumeMounts:
            - name: dags-volume
              mountPath: "/dags-folder"
            - name: exec-script
              mountPath: /scripts/exec-cronjob.sh
              subPath: exec-cronjob.sh
          volumes:
          - name: dags-volume
            persistentVolumeClaim:
              claimName: airflow-dags-pvc
          - name: exec-script
            configMap:
              name: exec-cronjob-configmap
              items:
              - key: "exec-cronjob.sh"
                path: "exec-cronjob.sh"
          restartPolicy: OnFailure
