apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sync
spec:
  schedule: {{ .Values.cronJob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: git-sync-cronjob
            image: ubuntu:24.10
            args:
            - chmod +x /scripts/exec-cronjob.sh
            - /scripts/exec-cronjob.sh
            volumeMounts:
            - name: dags-volume
              mountPath: "/dags-folder"
          volumes:
          - name: dags-volume
            persistentVolumeClaim:
              claimName: airflow-dags-pvc
          restartPolicy: OnFailure
